// AUTO-GENERATED by scripts/gen-image-map.js — do not edit by hand.
/* eslint-disable */
export const INGREDIENT_IMAGES: Record<string, any> = {

};

export const DISH_IMAGES: Record<string, any> = {

};
